<a href="https://colab.research.google.com/github/ayush9492/GenAi/blob/main/Text_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bag of words

In [2]:
import numpy as np
import pandas as pd

In [3]:
# 1) Basic bag of words using countvectorizer

from sklearn.feature_extraction.text import CountVectorizer

# Sample text data
texts = [
    "The cat sat on the mat",
    "The dog sat on the floor",
    "Cats and dogs are pets"
]

# Create and fit CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

# Get feature names (words)
print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", X.toarray())

Vocabulary: ['and' 'are' 'cat' 'cats' 'dog' 'dogs' 'floor' 'mat' 'on' 'pets' 'sat'
 'the']
BoW Matrix:
 [[0 0 1 0 0 0 0 1 1 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 1 2]
 [1 1 0 1 0 1 0 0 0 1 0 0]]


In [16]:
df = pd.DataFrame({"text":["The cat sat on the mat",
    "The dog sat on the floor",
    "Cats and dogs are pets"],"output":[1,0,1]})

from sklearn.feature_extraction.text import CountVectorizer

# Create and fit CountVectorizer
cv = CountVectorizer()

bow = cv.fit_transform(df['text'])
print("Vocabulary:",cv.vocabulary_)
bow.toarray()

Vocabulary: {'the': 11, 'cat': 2, 'sat': 10, 'on': 8, 'mat': 7, 'dog': 4, 'floor': 6, 'cats': 3, 'and': 0, 'dogs': 5, 'are': 1, 'pets': 9}


array([[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2],
       [1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0]])

In [18]:
cv.transform(["The cat dog sat on the mat"]).toarray()

array([[0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 2]])

In [20]:
x = bow.toarray()
y = df['output']

In [23]:
x

array([[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2],
       [1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0]])

# N-Grams

In [25]:
# Basic n-grams types:

text = "The quick brown fox"

# Unigrams (n=1)
unigrams = ['The', 'quick', 'brown', 'fox']

# Bigrams (n=2)
bigrams = ['The quick', 'quick brown', 'brown fox']

# Trigrams (n=3)
trigrams = ['The quick brown', 'quick brown fox']